import Anthropic from "@anthropic-ai/sdk";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import { z } from "zod";
import type { AgentSchema } from "./types";
import { FieldRoleSchema, FieldTypeSchema } from "./types";

/* ------------------------------------------------------------------ */
/* Semantic Annotator — the ONLY LLM step in the generation pipeline.  */
/*                                                                     */
/* It supplies presentation metadata (labels, panel titles, field-type */
/* hints, placeholder roles) for keys the Structural Parser already    */
/* extracted. It can never add or remove a field: the merger iterates  */
/* over the parser's keys and merely looks up annotations, so invented */
/* keys are ignored and missing keys fall back deterministically.      */
/*                                                                     */
/* Failure path: 1 retry with the error as context, then null → the    */
/* merger degrades to template-label / titleCase quality. Never throws.*/
/* ------------------------------------------------------------------ */

export const AnnotationsSchema = z.object({
  agentTitle: z.string(),
  inputPanelTitle: z.string(),
  placeholders: z.array(
    z.object({
      key: z.string(),
      label: z.string(),
      type: FieldTypeSchema,
      role: FieldRoleSchema,
    })
  ),
  actions: z.array(
    z.object({
      toolName: z.string(),
      label: z.string(),
      params: z.array(
        z.object({
          key: z.string(),
          label: z.string(),
          type: FieldTypeSchema,
        })
      ),
    })
  ),
  outputPanelTitle: z.string(),
  outputDescription: z.string(),
});
export type Annotations = z.infer<typeof AnnotationsSchema>;

export interface AnnotationResult {
  annotations: Annotations | null;
  source: "llm" | "fallback";
  model?: string;
  error?: string;
}

const ANNOTATOR_SYSTEM = `You annotate an auto-generated human validation UI for an AI agent.
You receive the agent's system prompt, the {{placeholder}} keys of its user prompt template (with the template text that precedes each one), its tool signatures, and any trailing template text.

Return presentation metadata only. Rules:
- Echo every placeholder key and tool/parameter name EXACTLY as given. Keys may contain typos; never correct a key itself, only make the human-facing label correct (e.g. key "custome_mail" may be labeled "Email Content").
- Labels are short and human-friendly (1-4 words), written for a business reviewer, not a developer.
- Placeholder roles: "primary" = the per-run input the reviewer must read to validate the run (e.g. the customer's message or the source document); "context" = static instructions or configuration that rarely changes per run; "retrieved" = looked-up reference data (historical examples, RAG results, pricing tables).
- Field type hints: "currency" for monetary amounts (check the tool description), "email" for email addresses, "longtext" for multi-line documents/mails/lists, "number" for plain numeric values, "boolean" for flags, "text" for short strings.
- agentTitle: a short title for this agent (e.g. "Acme Customer Support").
- outputPanelTitle/outputDescription: name the free-text output the agent generates after the trailing template text (e.g. trailing "answer :" for a support agent → "Suggested Reply" / "Reply generated by the Assistant").`;

function describeSchema(schema: AgentSchema): string {
  return JSON.stringify(
    {
      system_prompt: schema.systemPrompt,
      placeholders: schema.placeholders.map((p) => ({
        key: p.key,
        preceding_template_text: p.labelBefore,
      })),
      tools: schema.tools.map((t) => ({
        name: t.name,
        description: t.description,
        params: t.params.map((p) => ({ name: p.name, type: p.rawType || "unknown", required: p.required })),
      })),
      trailing_template_text: schema.trailingText,
    },
    null,
    2
  );
}

const MODEL = process.env.ANTHROPIC_MODEL ?? "claude-opus-4-8";

export async function annotate(schema: AgentSchema): Promise<AnnotationResult> {
  if (!process.env.ANTHROPIC_API_KEY) {
    return { annotations: null, source: "fallback", error: "ANTHROPIC_API_KEY not set" };
  }

  // Shared assessment keys: cap output and retries on every call.
  const client = new Anthropic({ maxRetries: 1 });
  const description = describeSchema(schema);

  let lastError = "";
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const response = await client.messages.parse({
        model: MODEL,
        max_tokens: 4096,
        system: ANNOTATOR_SYSTEM,
        messages: [
          {
            role: "user",
            content:
              attempt === 0
                ? `Annotate this agent definition:\n${description}`
                : `Annotate this agent definition:\n${description}\n\nYour previous attempt failed validation: ${lastError}. Follow the schema exactly.`,
          },
        ],
        output_config: { format: zodOutputFormat(AnnotationsSchema) },
      });

      if (response.parsed_output) {
        return { annotations: response.parsed_output, source: "llm", model: MODEL };
      }
      lastError = "response did not match the expected JSON schema";
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
    }
  }

  return { annotations: null, source: "fallback", error: lastError };
}
