import type { Annotations } from "./annotator";
import type { AgentSchema, BaseType, Field, FieldType, ToolAction, UISpec } from "./types";
import { isMutatingTool } from "./parser";

/* ------------------------------------------------------------------ */
/* Merger — deterministic join of ground truth and annotations.        */
/*                                                                     */
/* Iterates over the PARSER's keys only: the LLM cannot add, drop or   */
/* retype a field. Annotations refine presentation within the limits   */
/* of the structural type (a float may present as currency, never as   */
/* text); anything missing falls back to the template label or         */
/* titleCase(key). Never throws, never returns an invalid UISpec.      */
/* ------------------------------------------------------------------ */

export function titleCase(key: string): string {
  return key
    .split(/[_\s]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/** Field types a given structural base type may present as. First entry = default. */
const COMPATIBLE: Record<BaseType | "placeholder", FieldType[]> = {
  placeholder: ["longtext", "text", "email"],
  str: ["text", "longtext", "email"],
  float: ["number", "currency"],
  int: ["number", "currency"],
  bool: ["boolean"],
  unknown: ["unknown", "text", "longtext", "number", "currency", "email", "boolean"],
};

function resolveType(structural: BaseType | "placeholder", hint: FieldType | undefined): FieldType {
  const allowed = COMPATIBLE[structural];
  return hint && allowed.includes(hint) ? hint : allowed[0];
}

export function mergeToUISpec(schema: AgentSchema, annotations: Annotations | null): UISpec {
  const annPlaceholders = new Map(annotations?.placeholders.map((p) => [p.key, p]) ?? []);
  const annActions = new Map(annotations?.actions.map((a) => [a.toolName, a]) ?? []);

  const inputFields: Field[] = schema.placeholders.map((p) => {
    const ann = annPlaceholders.get(p.key);
    return {
      key: p.key,
      label: ann?.label ?? p.labelBefore ?? titleCase(p.key),
      type: resolveType("placeholder", ann?.type),
      required: true,
      // Without annotations we cannot tell primary from context — show everything
      // prominently rather than hide a field the reviewer might need.
      role: ann?.role ?? "primary",
    };
  });

  const actions: ToolAction[] = schema.tools.map((tool) => {
    const ann = annActions.get(tool.name);
    const annParams = new Map(ann?.params.map((p) => [p.key, p]) ?? []);
    return {
      toolName: tool.name,
      label: ann?.label ?? titleCase(tool.name),
      mutating: isMutatingTool(tool.name),
      fields: tool.params.map((param) => {
        const pAnn = annParams.get(param.name);
        return {
          key: param.name,
          label: pAnn?.label ?? titleCase(param.name),
          type: resolveType(param.baseType, pAnn?.type),
          required: param.required, // structural fact — never taken from the LLM
        };
      }),
    };
  });

  const trailingFallback = schema.trailingText
    ? titleCase(schema.trailingText.replace(/[:\s]+$/, ""))
    : "Generated Output";

  return {
    version: 1,
    agentTitle: annotations?.agentTitle ?? "Agent Validation",
    inputPanel: {
      title: annotations?.inputPanelTitle ?? "Informations",
      fields: inputFields,
    },
    actionsPanel: {
      title: "Actions performed by the assistant",
      actions,
    },
    outputPanel: {
      title: annotations?.outputPanelTitle ?? trailingFallback,
      type: "generated-text",
      description: annotations?.outputDescription ?? "Output generated by the assistant",
    },
  };
}
